name: Bug
description: Reporte de defecto
title: "[BUG] Título del bug"
labels: ["type: bug","status: todo"]
body:
  - type: textarea
    id: pasos
    attributes:
      label: Pasos para reproducir
      placeholder: "1) ... 2) ... 3) ..."
    validations:
      required: true
  - type: textarea
    id: esperado
    attributes:
      label: Resultado esperado
    validations:
      required: true
  - type: textarea
    id: obtenido
    attributes:
      label: Resultado obtenido
    validations:
      required: true
