name: Feature
description: Nueva capacidad o mejora
title: "[FEAT] Título de la feature"
labels: ["type: feature","status: todo"]
body:
  - type: textarea
    id: descripcion
    attributes:
      label: Descripción
      placeholder: "Como [rol] quiero [función] para [beneficio]"
    validations:
      required: true
  - type: input
    id: criterio
    attributes:
      label: Criterio de aceptación (resumen)
      placeholder: "Dado/Cuando/Entonces..."
    validations:
      required: true
