
# ----------------------------------------------------------------------------------
# Issue Template para MÓDULOS — .github/ISSUE_TEMPLATE/module.yml
# ----------------------------------------------------------------------------------

name: "📦 Módulo (visible en roadmap)"
description: "Estandariza la definición de un MÓDULO que aparecerá en la página pública"
title: "feat(module): <nombre-corto>"
labels: ["module", "status:planificado", "status:triage"]
body:
  - type: markdown
    attributes:
      value: |
        Este template crea un **MÓDULO** que se reflejará en la página pública vía `modules.json` (sincronizado por Action).
        Asegúrate de asignar **Milestone** (para ETA) y **Assignee(s)** (propietario).

  - type: input
    id: nombre
    attributes:
      label: Nombre del módulo
      placeholder: "Catálogo de Servicios Profesionales"
    validations:
      required: true

  - type: textarea
    id: descripcion
    attributes:
      label: Descripción (primer párrafo se muestra)
      description: "Qué hace el módulo y para quién. El primer párrafo se usa en cards."
      placeholder: |
        Permite publicar y gestionar servicios profesionales con categoría (lista), costo, moneda, método de pago, tiempo de entrega (SLA), imagen y enlace de ejemplo.
    validations:
      required: true

  - type: textarea
    id: acceptance
    attributes:
      label: Criterios de aceptación (Gherkin)
      placeholder: |
        Dado que soy Coordinador...
        Cuando creo un servicio con categoría, costo y tiempo de entrega...
        Entonces aparece en el catálogo y puedo ver su ETA y método de pago...

  - type: dropdown
    id: area
    attributes:
      label: Área
      options:
        - area:IAM
        - area:Programas
        - area:Expertos
        - area:Servicios
        - area:Dashboards
    validations:
      required: true

  - type: dropdown
    id: prioridad
    attributes:
      label: Prioridad
      options:
        - priority:P0
        - priority:P1
        - priority:P2
    validations:
      required: true

  - type: checkboxes
    id: dor
    attributes:
      label: Definition of Ready (DoR)
      options:
        - label: Usuario objetivo definido
        - label: Criterios de aceptación claros
        - label: Riesgos/Dependencias identificados
        - label: Estimación inicial acordada

  - type: textarea
    id: tasks
    attributes:
      label: Checklist (progreso automático)
      description: "Usa - [ ] / - [x]. El sync calculará % con base en esta lista."
      placeholder: |
        - [ ] Diseñar modelo de datos
        - [ ] Endpoint GET /servicios (paginado)
        - [ ] UI catálogo público

  - type: markdown
    attributes:
      value: |
        **Tip:** Si necesitas forzar un porcentaje manual, añade una línea `Progress: NN%` al cuerpo del Issue.



