name: Lint PR title (Conventional Commits)

on:
  pull_request:
    types: [opened, edited, synchronize, reopened]

jobs:
  semantic:
    runs-on: ubuntu-latest
    steps:
      - uses: amannn/action-semantic-pull-request@v5
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          titleOnly: true
          types: |
            chore
            docs
            feat
            fix
            refactor
            style
            test
            ci
            ops
          # Opción A: permitir 'graphql' como scope
          scopes: |
            module
            roadmap
            docs
            automation
            labels
            pages
            graphql
          # Opción B (en lugar de A): quita 'scopes' por completo para no restringirlos

