name: Sync modules.json from Issues

on:
  workflow_dispatch:
  schedule:
    - cron: '*/30 * * * *'

permissions:
  contents: write
  issues: read
  repository-projects: read

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.22.x'
          cache: true
          cache-dependency-path: |
            go.sum
            **/go.sum

      - name: Build sync tool
        run: |
          set -euo pipefail
          go mod tidy || true
          go build -o sync-modules ./cmd/sync-modules

      - name: Run sync
        env:
          GITHUB_TOKEN: ${{ github.token }}
          ORG: RON-DATADRIVEN
          PROJECT_NUMBER: '3'
          OUTPUT: docs/modules.json
        run: |
          set -euo pipefail
          ./sync-modules

      - name: Create Pull Request
        if: success()
        uses: peter-evans/create-pull-request@v6
        with:
          branch: chore/sync-modules-json
          title: 'chore: sync modules.json'
          commit-message: 'chore: sync modules.json'
          body: 'Actualización automática desde Project EOS 2.0'
