name: Sync modules.json from Issues

on:
  workflow_dispatch: {}
  schedule:
    - cron: '*/30 * * * *'  # cada 30 minutos

permissions:
  contents: write   # para commitear modules.json
  issues: read

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.22.x'

      - name: Build sync tool
        run: |
          go mod tidy
          go build -o sync-modules ./cmd/sync-modules

      - name: Run sync
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          REPO_SLUG: ${{ github.repository }} # owner/repo
          OUTPUT: docs/modules.json
          MODULE_LABEL: module
        run: |
          ./sync-modules

      - name: Commit & push if changed
        run: |
          if ! git diff --quiet -- docs/modules.json; then
            git config user.name "github-actions[bot]"
            git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
            git add docs/modules.json
            git commit -m "chore(roadmap): sync modules.json from Issues [skip ci]"
            git push
          else
            echo "No changes to commit."
          fi
