name: Validate modules.json

on:
  push:
    paths:
      - 'docs/modules.json'
  pull_request:
    paths:
      - 'docs/modules.json'

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with: { node-version: '20' }
      - name: Install ajv-cli
        run: npm i -g ajv-cli
      - name: Validate JSON
        run: ajv validate -s docs/modules.schema.json -d docs/modules.json --strict=false
